  
# This is a basic workflow to help you get started with Actions

name: Deploy package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Get the salesforce command line tool, extract it untar it and then install it
      - name: 'Build and Deploy'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
          
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET_D }}
            
      # sudo npm install sfdx-git-delta@latest -g  
      - name: Install App and Create Delta
        run: |
          sudo npm install sfdx-git-delta@latest -g
          git fetch --all
          git --no-pager diff --name-status origin/dev origin/master
          sgd --to origin/dev --from origin/master --repo . --output ./test/package1.xml
          cat test/package1.xml
      
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test/package1.xml 
          
      - name: Convert Metadata
        run: sfdx force:source:convert --manifest=test/package1.xml --outputdir=convert

      - name: Run Tests and Deploy
        run: sfdx force:mdapi:deploy --deploydir=convert --testlevel=RunLocalTests --checkonly -w30
      
      - run: mkdir -p path/to/artifact

      - run: |
          echo hello > path/to/artifact/world.txt
          cat path/to/artifact/world.txt

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
